// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pabjabbesaonwezbhcor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhYmphYmJlc2FvbndlemJoY29yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MDcwMjMsImV4cCI6MjA2NDQ4MzAyM30.M3PpTvI39YcKuElabqXxxSRz4pdB0SoaoSRziYF4Wr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);